# Generated by Django 5.2.7 on 2026-03-10 00:00

from django.db import migrations, models


def sync_existing_user_roles(apps, schema_editor):
    User = apps.get_model("user", "User")
    User.objects.filter(is_staff=True).update(role="admin")
    User.objects.filter(is_staff=False).update(role="normal")


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_address_options_alter_user_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("normal", "普通用户"), ("admin", "管理员"), ("merchant", "商家")],
                default="normal",
                max_length=20,
                verbose_name="角色",
            ),
        ),
        migrations.RunPython(sync_existing_user_roles, migrations.RunPython.noop),
    ]
