# Generated by Django 5.2.7 on 2026-03-10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_update_staff_by_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="QualificationApplication",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "application_type",
                    models.CharField(
                        choices=[("merchant", "商家资质"), ("staff", "工作人员资质")],
                        max_length=20,
                        verbose_name="申请类型",
                    ),
                ),
                ("reason", models.TextField(max_length=1000, verbose_name="申请说明")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "待审核"), ("approved", "已通过"), ("rejected", "已驳回")],
                        default="pending",
                        max_length=20,
                        verbose_name="审核状态",
                    ),
                ),
                ("review_note", models.CharField(blank=True, default="", max_length=255, verbose_name="审核备注")),
                ("reviewed_at", models.DateTimeField(blank=True, null=True, verbose_name="审核时间")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_qualification_applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核人",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qualification_applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="申请用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "资质申请",
                "verbose_name_plural": "资质申请",
                "ordering": ["-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="qualificationapplication",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("user", "application_type", "status"),
                name="uniq_pending_qualification_application",
            ),
        ),
    ]
