# Generated by Django 5.2.7 on 2026-03-07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeBanner",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100, verbose_name="标题")),
                ("image_url", models.URLField(max_length=500, verbose_name="轮播图")),
                ("link", models.CharField(blank=True, default="", max_length=255, verbose_name="跳转链接")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                ("sort", models.PositiveIntegerField(default=0, verbose_name="排序")),
            ],
            options={
                "verbose_name": "首页轮播",
                "verbose_name_plural": "首页轮播",
                "ordering": ["sort", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, verbose_name="分类名称")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                ("sort", models.PositiveIntegerField(default=0, verbose_name="排序")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="product.productcategory",
                        verbose_name="父级分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品分类",
                "verbose_name_plural": "商品分类",
                "ordering": ["sort", "id"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="商品名称")),
                ("subtitle", models.CharField(blank=True, default="", max_length=200, verbose_name="副标题")),
                ("cover_url", models.URLField(max_length=500, verbose_name="封面图")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="价格")),
                ("stock", models.PositiveIntegerField(default=0, verbose_name="库存")),
                ("sales", models.PositiveIntegerField(default=0, verbose_name="销量")),
                ("is_hot", models.BooleanField(default=False, verbose_name="热门推荐")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否上架")),
                ("description", models.TextField(blank=True, default="", verbose_name="商品描述")),
                ("specs", models.JSONField(blank=True, default=dict, verbose_name="规格信息")),
                (
                    "customer_service_hint",
                    models.CharField(blank=True, default="联系客服获取更多详情", max_length=200, verbose_name="客服提示"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="product.productcategory",
                        verbose_name="所属分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品",
                "verbose_name_plural": "商品",
                "ordering": ["-is_hot", "-sales", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image_url", models.URLField(max_length=500, verbose_name="图片地址")),
                ("sort", models.PositiveIntegerField(default=0, verbose_name="排序")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="product.product",
                        verbose_name="商品",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品图片",
                "verbose_name_plural": "商品图片",
                "ordering": ["sort", "id"],
            },
        ),
        migrations.CreateModel(
            name="ServiceMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.TextField(verbose_name="留言内容")),
                ("reply", models.TextField(blank=True, default="", verbose_name="客服回复")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_messages",
                        to="product.product",
                        verbose_name="商品",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "客服留言",
                "verbose_name_plural": "客服留言",
                "ordering": ["-id"],
            },
        ),
    ]
